# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tailor"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Loveless"]
  s.date = "2011-09-26"
  s.description = "ruby style checking tool"
  s.email = ["steve.loveless@gmail.com"]
  s.executables = ["tailor"]
  s.extra_rdoc_files = [
    "ChangeLog.rdoc",
    "README.rdoc"
  ]
  s.files = [
    ".gemtest",
    ".rspec",
    "ChangeLog.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "bin/tailor",
    "features/case_checking.feature",
    "features/indentation.feature",
    "features/spacing.feature",
    "features/spacing/commas.feature",
    "features/step_definitions/case_checking_steps.rb",
    "features/step_definitions/indentation_steps.rb",
    "features/step_definitions/spacing/commas_steps.rb",
    "features/step_definitions/spacing_steps.rb",
    "features/support/1_file_with_bad_comma_spacing/bad_comma_spacing.rb",
    "features/support/1_file_with_bad_curly_brace_spacing/bad_curly_brace_spacing.rb",
    "features/support/1_file_with_bad_operator_spacing/bad_op_spacing.rb",
    "features/support/1_file_with_bad_parenthesis/bad_parenthesis.rb",
    "features/support/1_file_with_bad_square_brackets/bad_square_brackets.rb",
    "features/support/1_file_with_bad_ternary_colon_spacing/bad_ternary_colon_spacing.rb",
    "features/support/1_file_with_camel_case_class/camel_case_class.rb",
    "features/support/1_file_with_camel_case_method/camel_case_method.rb",
    "features/support/1_file_with_hard_tabs/hard_tab.rb",
    "features/support/1_file_with_long_lines/long_lines.rb",
    "features/support/1_file_with_snake_case_class/snake_case_class.rb",
    "features/support/1_file_with_snake_case_method/snake_case_method.rb",
    "features/support/1_file_with_trailing_whitespace/trailing_whitespace.rb",
    "features/support/1_good_simple_file/simple_project.rb",
    "features/support/1_long_file_with_indentation/my_project.rb",
    "features/support/common.rb",
    "features/support/env.rb",
    "features/support/matchers.rb",
    "features/support/world.rb",
    "lib/tailor.rb",
    "lib/tailor/file_line.rb",
    "lib/tailor/indentation.rb",
    "lib/tailor/spacing.rb",
    "spec/file_line_spec.rb",
    "spec/indentation_spec.rb",
    "spec/spacing/colon_spacing_spec.rb",
    "spec/spacing/comma_spacing_spec.rb",
    "spec/spacing/curly_brace_spacing_spec.rb",
    "spec/spacing/parentheses_spacing_spec.rb",
    "spec/spacing/square_bracket_spacing_spec.rb",
    "spec/spacing_spec.rb",
    "spec/spec_helper.rb",
    "spec/tailor_spec.rb",
    "tailor.gemspec",
    "tasks/metrics.rake",
    "tasks/rspec.rake",
    "tasks/stats.rake"
  ]
  s.homepage = "http://github.com/turboladen/tailor"
  s.post_install_message = ["\n", "Thanks for checking out Tailor.  To run, simply do:\n", "  # tailor [directory to check]\n", "\n", "  -OR-\n", "  \n", "  # tailor [.rb/.erb file to check]\n", "\n", "\n", "For more information on tailor, see http://github.com/turboladen/tailor\n"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Utility for checking style of Ruby files."
  s.test_files = [
    "spec/file_line_spec.rb",
    "spec/indentation_spec.rb",
    "spec/spacing/colon_spacing_spec.rb",
    "spec/spacing/comma_spacing_spec.rb",
    "spec/spacing/curly_brace_spacing_spec.rb",
    "spec/spacing/parentheses_spacing_spec.rb",
    "spec/spacing/square_bracket_spacing_spec.rb",
    "spec/spacing_spec.rb",
    "spec/spec_helper.rb",
    "spec/tailor_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 1.0.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.12"])
      s.add_development_dependency(%q<code_statistics>, ["= 0.2.13"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.10.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<metric_fu>, [">= 2.0.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.8"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 1.0.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.12"])
      s.add_development_dependency(%q<code_statistics>, ["~> 0.2.13"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.10.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<metric_fu>, [">= 2.0.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.8"])
    else
      s.add_dependency(%q<term-ansicolor>, [">= 1.0.5"])
      s.add_dependency(%q<bundler>, ["~> 1.0.12"])
      s.add_dependency(%q<code_statistics>, ["= 0.2.13"])
      s.add_dependency(%q<cucumber>, ["~> 0.10.2"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<metric_fu>, [">= 2.0.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.8"])
      s.add_dependency(%q<term-ansicolor>, [">= 1.0.5"])
      s.add_dependency(%q<bundler>, ["~> 1.0.12"])
      s.add_dependency(%q<code_statistics>, ["~> 0.2.13"])
      s.add_dependency(%q<cucumber>, ["~> 0.10.2"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<metric_fu>, [">= 2.0.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.8"])
    end
  else
    s.add_dependency(%q<term-ansicolor>, [">= 1.0.5"])
    s.add_dependency(%q<bundler>, ["~> 1.0.12"])
    s.add_dependency(%q<code_statistics>, ["= 0.2.13"])
    s.add_dependency(%q<cucumber>, ["~> 0.10.2"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<metric_fu>, [">= 2.0.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.8"])
    s.add_dependency(%q<term-ansicolor>, [">= 1.0.5"])
    s.add_dependency(%q<bundler>, ["~> 1.0.12"])
    s.add_dependency(%q<code_statistics>, ["~> 0.2.13"])
    s.add_dependency(%q<cucumber>, ["~> 0.10.2"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<metric_fu>, [">= 2.0.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.8"])
  end
end

